export {default as axiosClient} from './axiosClient';
export { default as authAPI } from './authAPI';
export { default as movieAPI } from './movieAPI';
export { default as groupTheaterAPI } from './groupTheaterAPI';
export { default as reviewAPI } from './reviewAPI';
export { default as showtimeAPI } from './showtimeAPI';
export { default as ticketAPI } from './ticketAPI';
export { default as adminAPI } from './adminAPI';
export {default as newsAPI} from './newsAPI';
export {default as reservationsAPI} from './reservationsAPI';